Convert the following .catch to .then handler

let promise = new Promise(function(resolve,reject)){
    reject("Rejected!")
}

promise.catch(function(err){
    return err;
})